version: '3.1'
services:
  mongo:
    image: mongo
    dns:
      - ${NAMESERVER}
    restart: always
    container_name: ${CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${INITDB_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}:/data/db
    ports:
      - ${MONGO_PORT}:27017